import { createSeedClient } from '@snaplet/seed';

// You can use @snaplet/copycat to generate fake data for a field, for example:
// ```
// await seed.users([{ email: ({ seed }) => copycat.email(seed) }])
// ```
// More on this in our docs: https://docs.snaplet.dev/core-concepts/seed#inside-the-snapletseed-workflow
import { copycat } from '@snaplet/copycat'

// This is a basic example generated by Snaplet to start you off, check out the docs for where to go from here
// * For more on getting started with @snaplet/seed: https://docs.snaplet.dev/getting-started/quick-start/seed
// * For a more detailed reference: https://docs.snaplet.dev/core-concepts/seed


const seed = await createSeedClient({
  dryRun: process.env.DRY !== '0',
});

// Clears all existing data in the database, but keep the structure
await seed.$resetDatabase()


await seed.agents([
  {
    id: '22b18ea191b9c3060217b5e745d075ba',
    name: 'Echo'
  },
  {
    id: '7d45697beaf8740e92bc163c72f71e2b',
    name: 'Paola'
  },
  {
    id: '3af24d4268ee5bb0981827f04bbc71dc',
    name: 'Shimmer'
  },
  {
    id: '75f5073840d895e63bc452854b9b7c7b',
    name: 'Onyx'
  }
]);

// Run it with: DRY=0 npx tsx seed.mts
