import { useState, useEffect } from "react";
import { generateImage } from "@/libs/wai";

type ImageGeneratorProps = {
  transcript: string[];
};

const ImageGenerator = ({ transcript }: ImageGeneratorProps) => {
  const [imageUrls, setImageUrls] = useState<any>([]);
  const [displayIndex, setDisplayIndex] = useState<number | null>(null);

  useEffect(() => {
    if (transcript.length === 0) {
      return;
    }

    const fetchImage = async () => {

      for (let i = imageUrls.length; i < transcript.length; i++) {
        let backstory = "";
        let firstImage = i === 0;
        if (!firstImage) {
          for (let j = 0; j < i; j++) {
            backstory += transcript[j];
          }
        }
        const url = await generateImage(imagePrompt(firstImage, transcript[i], backstory));
        setImageUrls((prevUrls: string[]) => [...prevUrls, url.imageUrl]);
      }
    };

    fetchImage();
  }, [transcript]);

  // updates which image should display when imageUrls changes
  useEffect(() => {
    setDisplayIndex(imageUrls.length > 0 ? imageUrls.length - 1 : null);
  }, [imageUrls]);

  const stylingGuidelines = `
  **Art Style Guidelines:**
  - The illustrations should have a whimsical and imaginative feel, with bright and cheerful colors.
  - The style should be hand-drawn and slightly cartoonish, with soft edges and gentle shading.
  - Characters and settings should be drawn with soft, rounded lines and vibrant colors.
  - Ensure a consistent design for all characters, with expressive features and a slightly cartoonish appearance to appeal to young readers.
  - Maintain a rich and varied color palette that complements the natural setting. For forest scenes, use greens, browns, and golds; for water scenes, use blues and greens, etc.
  - All illustrations should match these guidelines to ensure a cohesive and harmonious visual style throughout the story.
  - Make sure no text is drawn in the image.
  `;

  function imagePrompt(firstImage: boolean, story: string, backStory?: string) {
    let prompt = stylingGuidelines;

    if (firstImage) {
      prompt += `This is the first image in the series so there isn't a backstory. `;
    } else {
      prompt += `Previous backstory: ${backStory} `;
    }

    prompt += `With these art style guidelines and backstory in mind if there is one, please illustrate the following: ${story}`;

    return prompt;
  }

  return (
    <div className="flex-grow flex justify-center">
      {displayIndex !== null && 
        <div>
          <img key={displayIndex} src={imageUrls[displayIndex]} alt={`Generated by DALL-E ${3}`} className="m-2" />
        </div>
      }
    </div>
  );
};

export default ImageGenerator;