name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: supabase/setup-cli@v1
        name: Setup Supabase CLI
        with:
          version: latest

      - name: Link Supabase Project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - name: Push Migrations to Staging
        run: supabase db push
  
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      DOMAIN: wai-staging.hatchmatter.com
      TEAM: hatchmatter-projects

    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_TOKEN
      - name: Deploy Project Artifacts to Vercel and Alias Staging Domain
        run: bash bin/deploy-staging.sh
